[package]
name = "my-gtk-app"
version = "0.1.0"
edition = "2024"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_16"] }
markdown = "1.0.0"
relm4 = "0.9.1"
relm4-components = "0.9.1"
webkit6 = "0.4.0"
